### ISSUE TITLE
FileNotFoundError: Missing '6D_meanpose.npz' when running test.py

### ISSUE THREAD

**Issue by fjz3334** [Celiali/Dessie#1]
### Description

I encountered a FileNotFoundError when running the test.py file in the Dessie project. The error log is as follows:

```python
Traceback (most recent call last):
  File "test.py", line 117, in <module>
    Model, trainer = get_model(args, args.ckpt_file, device)
  File "test.py", line 25, in get_model
    vanilla = VanillaUpdateTrainer(opts=args)
  File "/databank/home/user/project/Dessie-main/code/src/trainer/vanillaupdatetrainer.py", line 27, in __init__
    self.model = DESSIE(opts)
  File "/databank/home/user/project/Dessie-main/code/src/model/dessie.py", line 87, in __init__
    mean_params = np.load(os.path.join(opts.model_dir, '6D_meanpose.npz'), allow_pickle=True)['mean_pose'].astype(
  File "/databank/home/user/anaconda3/envs/dessie/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/databank/home/user/project/Dessie-main/code/src/SMAL/smpl_models/6D_meanpose.npz'
```

### Steps to Reproduce

1. Clone the `Dessie` repository.
2. Follow the README instructions to download the `hSMAL` model and place it under the `./code/src/SMAL/smpl_models` folder.
3. Run the `test.py` script:

```bash
python test.py
```

4. Observe the `FileNotFoundError` indicating the missing file `6D_meanpose.npz`.

### What I Have Tried

1. Verified that the `hSMAL` model files were downloaded and placed correctly in the `./code/src/SMAL/smpl_models` folder.
2. Checked the README for any additional instructions regarding `6D_meanpose.npz`, but found no relevant details.
3. Searched online for similar errors but could not find a solution.

### Analysis

According to the README, the `hSMAL` model was downloaded and placed in the correct directory. However, the script still reports a missing file `6D_meanpose.npz`.

* Is this file supposed to be manually generated or downloaded from somewhere else?
* Does the `hSMAL` model include this file? If so, it might indicate an issue with the downloaded model files

### Request for Help

1. Could you confirm whether the `6D_meanpose.npz` file needs to be manually generated or downloaded? If so, could you provide instructions or the link?
2. If the `6D_meanpose.npz` file is part of the `hSMAL` model, could you verify if the provided model files are complete?

Thank you for your support!

**Comment by Celiali** [comment]
Hi, thanks for your interest. The file is available at this [link](https://drive.google.com/file/d/1ZCyOqMRvjZhtDykG28NFxQBiUQ0qHn-D/view?usp=sharing).
